spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        show-sql: false

    h2:
        console:
            enabled: true
            path: /h2

    datasource:
        url: jdbc:h2:file:~/test1
        username: sa
        password:
        driver-class-name: org.h2.Driver